apiVersion: v1
kind: ServiceAccount
metadata:
  name: rise-riscv-runner-node-labeller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rise-riscv-runner-node-labeller
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rise-riscv-runner-node-labeller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rise-riscv-runner-node-labeller
subjects:
  - kind: ServiceAccount
    name: rise-riscv-runner-node-labeller
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rise-riscv-runner-node-labeller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: riscv-runner-device-plugin
    app.kubernetes.io/component: labeller
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: riscv-runner-device-plugin
      app.kubernetes.io/component: labeller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: riscv-runner-device-plugin
        app.kubernetes.io/component: labeller
    spec:
      serviceAccountName: rise-riscv-runner-node-labeller
      nodeSelector:
        kubernetes.io/arch: riscv64
      containers:
        - name: node-labeller
          image: rg.fr-par.scw.cloud/funcscwriseriscvrunnerappqdvknz9s/riscv-runner:node-labeller-latest
          imagePullPolicy: Always
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: device-tree
              mountPath: /sys/firmware/devicetree/base
              readOnly: true
          securityContext:
            privileged: true
      volumes:
        - name: device-tree
          hostPath:
            path: /sys/firmware/devicetree/base
